USE [WideWorldImporters]
GO

SELECT * FROM INFORMATION_SCHEMA.TABLES 
WHERE TABLE_TYPE='VIEW'
GO

USE [WideWorldImporters]
GO

SELECT * FROM INFORMATION_SCHEMA.TABLES 
WHERE TABLE_TYPE='BASE TABLE'
GO